### ISSUE TITLE
Add registration info

### ISSUE THREAD

**Issue by TomasVotruba** [nextras/latte-macros#6]
Also here would be nice to add extension to keep convention a save some time creating one.

Containing:
```php
$builder->getDefinition('nette.latteFactory')
	->addSetup('Nextras\Latte\Macros\RedefineMacro::install(?->getCompiler())', ['@self']);
```

Or at least add config registration to `readme.md`:

```yaml
latte:
    macros:
        - Nextras\Latte\Macros\RedefineMacro::install
```

(I don't use this approach, so correct me if incorrect.)
